spring:
  application:
    name: ms-customer
  h2:
    console:
      enabled: true
server:
  port: 9099
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: true
    registry-fetch-interval-seconds: 5
    refresh:
      enable: true
    
  healthcheck:
    enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    registry-fetch-interval-seconds: 5
